apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: mauron/api-test-sabado:7
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-config
